version: '3.1'

services:
  drop-token:
    build: .
    ports:
      - 8080:8080
    environment:
      SPRING_DATA_MONGODB_DATABASE: connect4
      SPRING_DATA_MONGODB_HOST: mongo
      SPRING_DATA_MONGODB_PORT: 27017
      MONGODB_HOST: mongo
  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017